name: Record RTSP Stream

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Runs the workflow every 5 minutes

jobs:
  record-stream:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # You can specify any compatible version

      # Step 3: Install dependencies (if you have any in package.json)
      - name: Install dependencies
        run: npm install

      # Step 4: Install ffmpeg
      - name: Install ffmpeg
        run: sudo apt-get install -y ffmpeg

      # Step 5: Run the recording script
      - name: Start recording RTSP stream
        run: node record.js
